const uuid4 = require('uuid').v4();

const nigerianStates = [
    {
      "id": uuid4,
      "state_id": "AB",
      "state_name": "Abia",
      "capital": "Umuahia",
      "motto": "God's Own State",
      "zone": "South East",
      "population_2026_projection": 4895000,
      "land_area_km2": 6320,
      "governor": "Alex Otti",
      "governor_party": "LP",
      "economic_activity": ["Agriculture", "Shoe Manufacturing", "Textiles"]
    },
    {
      "id": uuid4,
      "state_id": "AD",
      "state_name": "Adamawa",
      "capital": "Yola",
      "motto": "Land of Beauty",
      "zone": "North East",
      "population_2026_projection": 5210000,
      "land_area_km2": 36917,
      "governor": "Ahmadu Umaru Fintiri",
      "governor_party": "PDP",
      "economic_activity": ["Agriculture", "Fishery", "Cattle Rearing"]
    },
    {
      "id": uuid4,
      "state_id": "AK",
      "state_name": "Akwa Ibom",
      "capital": "Uyo",
      "motto": "Land of Promise",
      "zone": "South South",
      "population_2026_projection": 7200000,
      "land_area_km2": 7081,
      "governor": "Umo Eno",
      "governor_party": "PDP",
      "economic_activity": ["Oil & Gas", "Tourism", "Fishing"]
    },
    {
      "id": uuid4,
      "state_id": "AN",
      "state_name": "Anambra",
      "capital": "Awka",
      "motto": "Light of the Nation",
      "zone": "South East",
      "population_2026_projection": 6850000,
      "land_area_km2": 4844,
      "governor": "Charles Soludo",
      "governor_party": "APGA",
      "economic_activity": ["Commerce", "Manufacturing", "Metalworking"]
    },
    {
      "id": uuid4,
      "state_id": "BA",
      "state_name": "Bauchi",
      "capital": "Bauchi",
      "motto": "Pearl of Tourism",
      "zone": "North East",
      "population_2026_projection": 8300000,
      "land_area_km2": 45893,
      "governor": "Bala Mohammed",
      "governor_party": "PDP",
      "economic_activity": ["Tourism", "Agriculture", "Mining"]
    },
    {
      "id": uuid4,
      "state_id": "BY",
      "state_name": "Bayelsa",
      "capital": "Yenagoa",
      "motto": "Glory of all Lands",
      "zone": "South South",
      "population_2026_projection": 3100000,
      "land_area_km2": 10773,
      "governor": "Douye Diri",
      "governor_party": "PDP",
      "economic_activity": ["Oil & Gas", "Fishing", "Palm Oil"]
    },
    {
      "id": uuid4,
      "state_id": "BE",
      "state_name": "Benue",
      "capital": "Makurdi",
      "motto": "Food Basket of the Nation",
      "zone": "North Central",
      "population_2026_projection": 7150000,
      "land_area_km2": 34059,
      "governor": "Hyacinth Alia",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Food Processing"]
    },
    {
      "id": uuid4,
      "state_id": "BO",
      "state_name": "Borno",
      "capital": "Maiduguri",
      "motto": "Home of Peace",
      "zone": "North East",
      "population_2026_projection": 7600000,
      "land_area_km2": 70898,
      "governor": "Babagana Zulum",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Trade", "Livestock"]
    },
    {
      "id": uuid4,
      "state_id": "CR",
      "state_name": "Cross River",
      "capital": "Calabar",
      "motto": "The People's Paradise",
      "zone": "South South",
      "population_2026_projection": 4900000,
      "land_area_km2": 20156,
      "governor": "Bassey Otu",
      "governor_party": "APC",
      "economic_activity": ["Tourism", "Agriculture", "Quarrying"]
    },
    {
      "id": uuid4,
      "state_id": "DE",
      "state_name": "Delta",
      "capital": "Asaba",
      "motto": "The Big Heart",
      "zone": "South South",
      "population_2026_projection": 7300000,
      "land_area_km2": 17698,
      "governor": "Sheriff Oborevwori",
      "governor_party": "PDP",
      "economic_activity": ["Oil & Gas", "Agriculture", "Glass Manufacturing"]
    },
    {
      "id": uuid4,
      "state_id": "EB",
      "state_name": "Ebonyi",
      "capital": "Abakaliki",
      "motto": "Salt of the Nation",
      "zone": "South East",
      "population_2026_projection": 3900000,
      "land_area_km2": 5670,
      "governor": "Francis Nwifuru",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Mining (Salt/Lead)", "Rice Milling"]
    },
    {
      "id": uuid4,
      "state_id": "ED",
      "state_name": "Edo",
      "capital": "Benin City",
      "motto": "Heartbeat of the Nation",
      "zone": "South South",
      "population_2026_projection": 5100000,
      "land_area_km2": 19559,
      "governor": "Monday Okpebholo",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Arts & Culture", "Oil & Gas"]
    },
    {
      "id": uuid4,
      "state_id": "EK",
      "state_name": "Ekiti",
      "capital": "Ado Ekiti",
      "motto": "Land of Honour and Integrity",
      "zone": "South West",
      "population_2026_projection": 4100000,
      "land_area_km2": 6353,
      "governor": "Biodun Oyebanji",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Education", "Tourism"]
    },
    {
      "id": uuid4,
      "state_id": "EN",
      "state_name": "Enugu",
      "capital": "Enugu",
      "motto": "Coal City State",
      "zone": "South East",
      "population_2026_projection": 5500000,
      "land_area_km2": 7161,
      "governor": "Peter Mbah",
      "governor_party": "PDP",
      "economic_activity": ["Coal Mining", "Agriculture", "Trade"]
    },
    {
      "id": uuid4,
      "state_id": "FC",
      "state_name": "Federal Capital Territory",
      "capital": "Abuja",
      "motto": "Center of Unity",
      "zone": "North Central",
      "population_2026_projection": 4200000,
      "land_area_km2": 7315,
      "governor": "Nyesom Wike (Minister)",
      "governor_party": "PDP",
      "economic_activity": ["Administration", "Real Estate", "Construction"]
    },
    {
      "id": uuid4,
      "state_id": "GO",
      "state_name": "Gombe",
      "capital": "Gombe",
      "motto": "Jewel in the Savannah",
      "zone": "North East",
      "population_2026_projection": 4250000,
      "land_area_km2": 18768,
      "governor": "Muhammad Inuwa Yahaya",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Cement Manufacturing"]
    },
    {
      "id": uuid4,
      "state_id": "IM",
      "state_name": "Imo",
      "capital": "Owerri",
      "motto": "Eastern Heartlands",
      "zone": "South East",
      "population_2026_projection": 6900000,
      "land_area_km2": 5530,
      "governor": "Hope Uzodinma",
      "governor_party": "APC",
      "economic_activity": ["Oil & Gas", "Agriculture", "Commerce"]
    },
    {
      "id": uuid4,
      "state_id": "JI",
      "state_name": "Jigawa",
      "capital": "Dutse",
      "motto": "The New World",
      "zone": "North West",
      "population_2026_projection": 7500000,
      "land_area_km2": 23154,
      "governor": "Umar Namadi",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Livestock", "Trade"]
    },
    {
      "id": uuid4,
      "state_id": "KD",
      "state_name": "Kaduna",
      "capital": "Kaduna",
      "motto": "Centre of Learning",
      "zone": "North West",
      "population_2026_projection": 10200000,
      "land_area_km2": 46053,
      "governor": "Uba Sani",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Textiles", "Refining"]
    },
    {
      "id": uuid4,
      "state_id": "KN",
      "state_name": "Kano",
      "capital": "Kano",
      "motto": "Centre of Commerce",
      "zone": "North West",
      "population_2026_projection": 16500000,
      "land_area_km2": 20131,
      "governor": "Abba Kabir Yusuf",
      "governor_party": "NNPP",
      "economic_activity": ["Commerce", "Agriculture", "Manufacturing"]
    },
    {
      "id": uuid4,
      "state_id": "KT",
      "state_name": "Katsina",
      "capital": "Katsina",
      "motto": "Home of Hospitality",
      "zone": "North West",
      "population_2026_projection": 9900000,
      "land_area_km2": 24192,
      "governor": "Dikko Umaru Radda",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Cattle Rearing"]
    },
    {
      "id": uuid4,
      "state_id": "KE",
      "state_name": "Kebbi",
      "capital": "Birnin Kebbi",
      "motto": "Land of Equity",
      "zone": "North West",
      "population_2026_projection": 5800000,
      "land_area_km2": 36800,
      "governor": "Nasir Idris",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Fishing", "Tourism"]
    },
    {
      "id": uuid4,
      "state_id": "KO",
      "state_name": "Kogi",
      "capital": "Lokoja",
      "motto": "The Confluence State",
      "zone": "North Central",
      "population_2026_projection": 5600000,
      "land_area_km2": 29833,
      "governor": "Ahmed Usman Ododo",
      "governor_party": "APC",
      "economic_activity": ["Steel", "Agriculture", "Limestone"]
    },
    {
      "id": uuid4,
      "state_id": "KW",
      "state_name": "Kwara",
      "capital": "Ilorin",
      "motto": "State of Harmony",
      "zone": "North Central",
      "population_2026_projection": 4300000,
      "land_area_km2": 36825,
      "governor": "AbdulRahman AbdulRazaq",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Trade", "Services"]
    },
    {
      "id": uuid4,
      "state_id": "LA",
      "state_name": "Lagos",
      "capital": "Ikeja",
      "motto": "Centre of Excellence",
      "zone": "South West",
      "population_2026_projection": 17800000,
      "land_area_km2": 3577,
      "governor": "Babajide Sanwo-Olu",
      "governor_party": "APC",
      "economic_activity": ["Finance", "Tech", "Commerce", "Entertainment"]
    },
    {
      "id": uuid4,
      "state_id": "NA",
      "state_name": "Nasarawa",
      "capital": "Lafia",
      "motto": "Home of Solid Minerals",
      "zone": "North Central",
      "population_2026_projection": 3300000,
      "land_area_km2": 27117,
      "governor": "Abdullahi Sule",
      "governor_party": "APC",
      "economic_activity": ["Mining", "Agriculture", "Salt"]
    },
    {
      "id": uuid4,
      "state_id": "NI",
      "state_name": "Niger",
      "capital": "Minna",
      "motto": "The Power State",
      "zone": "North Central",
      "population_2026_projection": 7200000,
      "land_area_km2": 76363,
      "governor": "Mohammed Umar Bago",
      "governor_party": "APC",
      "economic_activity": ["Hydro Power", "Agriculture"]
    },
    {
      "id": uuid4,
      "state_id": "OG",
      "state_name": "Ogun",
      "capital": "Abeokuta",
      "motto": "Gateway State",
      "zone": "South West",
      "population_2026_projection": 7100000,
      "land_area_km2": 16981,
      "governor": "Dapo Abiodun",
      "governor_party": "APC",
      "economic_activity": ["Manufacturing", "Agriculture", "Mining"]
    },
    {
      "id": uuid4,
      "state_id": "ON",
      "state_name": "Ondo",
      "capital": "Akure",
      "motto": "Sunshine State",
      "zone": "South West",
      "population_2026_projection": 6100000,
      "land_area_km2": 15500,
      "governor": "Lucky Aiyedatiwa",
      "governor_party": "APC",
      "economic_activity": ["Cocoa", "Bitumen", "Oil & Gas"]
    },
    {
      "id": uuid4,
      "state_id": "OS",
      "state_name": "Osun",
      "capital": "Osogbo",
      "motto": "Land of Virtue",
      "zone": "South West",
      "population_2026_projection": 5700000,
      "land_area_km2": 9251,
      "governor": "Ademola Adeleke",
      "governor_party": "PDP",
      "economic_activity": ["Agriculture", "Gold Mining", "Cocoa"]
    },
    {
      "id": uuid4,
      "state_id": "OY",
      "state_name": "Oyo",
      "capital": "Ibadan",
      "motto": "Pace Setter State",
      "zone": "South West",
      "population_2026_projection": 9600000,
      "land_area_km2": 28454,
      "governor": "Seyi Makinde",
      "governor_party": "PDP",
      "economic_activity": ["Agriculture", "Trade", "Services"]
    },
    {
      "id": uuid4,
      "state_id": "PL",
      "state_name": "Plateau",
      "capital": "Jos",
      "motto": "Home of Peace and Tourism",
      "zone": "North Central",
      "population_2026_projection": 5300000,
      "land_area_km2": 30913,
      "governor": "Caleb Mutfwang",
      "governor_party": "PDP",
      "economic_activity": ["Tin Mining", "Tourism", "Agriculture"]
    },
    {
      "id": uuid4,
      "state_id": "RI",
      "state_name": "Rivers",
      "capital": "Port Harcourt",
      "motto": "Treasure Base of the Nation",
      "zone": "South South",
      "population_2026_projection": 9500000,
      "land_area_km2": 11077,
      "governor": "Siminalayi Fubara",
      "governor_party": "PDP",
      "economic_activity": ["Oil & Gas", "Fishery", "Construction"]
    },
    {
      "id": uuid4,
      "state_id": "SO",
      "state_name": "Sokoto",
      "capital": "Sokoto",
      "motto": "Seat of the Caliphate",
      "zone": "North West",
      "population_2026_projection": 6500000,
      "land_area_km2": 25973,
      "governor": "Ahmad Aliyu",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Leather Works"]
    },
    {
      "id": uuid4,
      "state_id": "TA",
      "state_name": "Taraba",
      "capital": "Jalingo",
      "motto": "Nature's Gift to the Nation",
      "zone": "North East",
      "population_2026_projection": 4100000,
      "land_area_km2": 54473,
      "governor": "Agbu Kefas",
      "governor_party": "PDP",
      "economic_activity": ["Agriculture", "Tea/Coffee", "Mining"]
    },
    {
      "id": uuid4,
      "state_id": "YO",
      "state_name": "Yobe",
      "capital": "Damaturu",
      "motto": "Pride of the Sahel",
      "zone": "North East",
      "population_2026_projection": 4500000,
      "land_area_km2": 45502,
      "governor": "Mai Mala Buni",
      "governor_party": "APC",
      "economic_activity": ["Agriculture", "Potash", "Livestock"]
    },
    {
      "id": uuid4,
      "state_id": "ZA",
      "state_name": "Zamfara",
      "capital": "Gusau",
      "motto": "Farming is Our Pride",
      "zone": "North West",
      "population_2026_projection": 5800000,
      "land_area_km2": 39762,
      "governor": "Dauda Lawal",
      "governor_party": "PDP",
      "economic_activity": ["Agriculture", "Gold Mining"]
    }
];

module.exports = nigerianStates;
