const uuid4 = require("uuid").v4;

const abia = {
  id: uuid4,
  code: "AB",
  state_name: "Abia",
  capital: "Umuahia",
  motto: "God's Own State",
  zone: "South East",
  cordinates: {
    lat: 5.45409529947607,
    lon: 7.5153071,
  },
  population: 4895000,
  land_area: 6320,
  governor: "Alex Otti",
  governor_party: "LP",
  economic_activity: ["Agriculture", "Shoe Manufacturing", "Textiles"],
  LGAs: {
    total: 17,
    LGA_data: [
      {
        name: "Aba North",
        headquarters: "Eziama",
        population: 155600,
        land_area: 23,
        mineral_resources: ["Commercial/Industrial Hub", "Sand", "Gravel"],
      },
      {
        name: "Aba South",
        headquarters: "Aba",
        population: 622400,
        land_area: 49,
        mineral_resources: ["Commercial/Industrial Hub", "Glass Sands"],
      },
      {
        name: "Arochukwu",
        headquarters: "Arochukwu",
        population: 246600,
        land_area: 524,
        mineral_resources: [
          "Limestone",
          "Gravel",
          "Sandstone",
          "Coal (Potential)",
          "Lead/Zinc",
        ],
      },
      {
        name: "Bende",
        headquarters: "Bende",
        population: 280500,
        land_area: 601,
        mineral_resources: [
          "Clay (Kaolinite)",
          "Phosphate",
          "Lignite",
          "Gold (Traces)",
        ],
      },
      {
        name: "Ikwuano",
        headquarters: "Isiala Oboro",
        population: 200800,
        land_area: 281,
        mineral_resources: ["Clay", "Sand", "Gravel"],
      },
      {
        name: "Isiala Ngwa North",
        headquarters: "Okpuala Ngwa",
        population: 224400,
        land_area: 283,
        mineral_resources: ["Kaolin", "Sand"],
      },
      {
        name: "Isiala Ngwa South",
        headquarters: "Omoba",
        population: 199000,
        land_area: 258,
        mineral_resources: ["Kaolin", "Agricultural Land"],
      },
      {
        name: "Isuikwuato",
        headquarters: "Mbalano",
        population: 168600,
        land_area: 360,
        mineral_resources: ["Iron Ore", "Kaolin", "Granite"],
      },
      {
        name: "Obingwa",
        headquarters: "Mgboko",
        population: 264900,
        land_area: 395,
        mineral_resources: [
          "Crude Oil (Pipelines)",
          "Sand",
          "Agricultural Resources",
        ],
      },
      {
        name: "Ohafia",
        headquarters: "Ebem Ohafia",
        population: 358200,
        land_area: 550,
        mineral_resources: ["Limestone", "Lead", "Zinc", "Lignite"],
      },
      {
        name: "Osisioma Ngwa",
        headquarters: "Osisioma",
        population: 321300,
        land_area: 198,
        mineral_resources: [
          "Natural Gas (Depots)",
          "Crude Oil (Pipelines)",
          "Sand",
        ],
      },
      {
        name: "Ugwunagbo",
        headquarters: "Ugwunagbo",
        population: 124300,
        land_area: 108,
        mineral_resources: ["Crude Oil (Obuzo deposit)", "Fine Sand"],
      },
      {
        name: "Ukwa East",
        headquarters: "Akwete",
        population: 85200,
        land_area: 254,
        mineral_resources: [
          "Sharp Sand (Azumini Blue River)",
          "Crude Oil",
          "Natural Gas",
        ],
      },
      {
        name: "Ukwa West",
        headquarters: "Oke Ikpe",
        population: 128000,
        land_area: 271,
        mineral_resources: [
          "Crude Oil (Major Producer)",
          "Natural Gas",
          "Clay",
        ],
      },
      {
        name: "Umuahia North",
        headquarters: "Umuahia",
        population: 324000,
        land_area: 245,
        mineral_resources: ["Kaolin", "Clay", "Limestone"],
      },
      {
        name: "Umuahia South",
        headquarters: "Apumiri",
        population: 204900,
        land_area: 140,
        mineral_resources: ["Kaolin", "Clay", "Sand"],
      },
      {
        name: "Umunneochi",
        headquarters: "Nkwoagu Isuochi",
        population: 242600,
        land_area: 368,
        mineral_resources: ["Granite", "Lead", "Zinc", "Laterite"],
      },
    ],
  },
};

module.exports = abia;