const uuid4 = require("uuid").v4;

const adamawa = {
  id: uuid4,
  code: "AD",
  state_name: "Adamawa",
  capital: "Yola",
  motto: "Land of Beauty",
  zone: "North East",
  cordinates: {
    lat: 9.512977199417053,
    lon: 12.388188699999999,
  },
  population: 5210000,
  land_area: 36917,
  governor: "Ahmadu Umaru Fintiri",
  governor_party: "PDP",
  economic_activity: ["Agriculture", "Fishery", "Cattle Rearing"],
  LGAs: {
    total: 21,
    LGA_data: [
      [
        {
          name: "Demsa",
          headquaters: "Demsa",
          population: 275100,
          land_area: 1771,
          mineral_resources: ["Limestone", "Clay", "Potash"],
        },
        {
          name: "Fufore",
          headquaters: "Fufore",
          population: 323000,
          land_area: 5169,
          mineral_resources: ["Limestone", "Iron Ore", "Uranium (Traces)"],
        },
        {
          name: "Ganye",
          headquaters: "Ganye",
          population: 262100,
          land_area: 2095,
          mineral_resources: ["Tantalite", "Cassiterite", "Lead", "Kaolin"],
        },
        {
          name: "Girei",
          headquaters: "Girei",
          population: 200200,
          land_area: 1040,
          mineral_resources: ["Ilmenite", "Monazite", "Zircon", "Gypsum"],
        },
        {
          name: "Gombi",
          headquaters: "Gombi",
          population: 227900,
          land_area: 2312,
          mineral_resources: ["Magnesite", "Kaolin", "Gypsum"],
        },
        {
          name: "Guyuk",
          headquaters: "Guyuk",
          population: 272200,
          land_area: 764,
          mineral_resources: ["Gypsum", "Limestone", "Coal (Lignite)"],
        },
        {
          name: "Hong",
          headquaters: "Hong",
          population: 260900,
          land_area: 2588,
          mineral_resources: ["Kaolin", "Ilmenite", "Monazite", "Zircon"],
        },
        {
          name: "Jada",
          headquaters: "Jada",
          population: 259700,
          land_area: 3583,
          mineral_resources: ["Cassiterite", "Lead", "Marble", "Tantalite"],
        },
        {
          name: "Lamurde",
          headquaters: "Lamurde",
          population: 171600,
          land_area: 1083,
          mineral_resources: ["Gypsum", "Limestone", "Tantalite"],
        },
        {
          name: "Madagali",
          headquaters: "Gulak",
          population: 208400,
          land_area: 957,
          mineral_resources: ["Granite", "Quartz", "Feldspar", "Mica"],
        },
        {
          name: "Maiha",
          headquaters: "Maiha",
          population: 169900,
          land_area: 1346,
          mineral_resources: ["Clay", "Laterite", "Granite"],
        },
        {
          name: "Mayo Belwa",
          headquaters: "Mayo Belwa",
          population: 235600,
          land_area: 1768,
          mineral_resources: ["Ilmenite", "Iron Ore", "Lithium", "Barite"],
        },
        {
          name: "Michika",
          headquaters: "Michika",
          population: 239400,
          land_area: 822,
          mineral_resources: ["Granite", "Rhyolite", "Feldspar", "Quartz"],
        },
        {
          name: "Mubi North",
          headquaters: "Mubi",
          population: 233600,
          land_area: 826,
          mineral_resources: ["Tantalite", "Limestone", "Kaolin", "Granite"],
        },
        {
          name: "Mubi South",
          headquaters: "Gella",
          population: 200400,
          land_area: 476,
          mineral_resources: ["Gypsum", "Limestone", "Tantalite"],
        },
        {
          name: "Numan",
          headquaters: "Numan",
          population: 141200,
          land_area: 804,
          mineral_resources: ["Gypsum", "Limestone", "Salt"],
        },
        {
          name: "Shelleng",
          headquaters: "Shelleng",
          population: 229000,
          land_area: 1381,
          mineral_resources: ["Barite", "Gypsum", "Amethyst"],
        },
        {
          name: "Song",
          headquaters: "Song",
          population: 301000,
          land_area: 4202,
          mineral_resources: ["Quartz", "Albite", "Barite", "Uranium (Traces)"],
        },
        {
          name: "Toungo",
          headquaters: "Toungo",
          population: 80500,
          land_area: 5646,
          mineral_resources: ["Beryl", "Copper", "Gold", "Lithium"],
        },
        {
          name: "Yola North",
          headquaters: "Jimeta",
          population: 307900,
          land_area: 67,
          mineral_resources: ["Construction Sand", "Gravel", "Granite"],
        },
        {
          name: "Yola South",
          headquaters: "Yola",
          population: 302500,
          land_area: 919,
          mineral_resources: ["Gypsum", "Limestone", "Cassiterite", "Clay"],
        },
      ],
    ],
  },
};

module.exports = adamawa;
