const uuid4 = require("uuid").v4;


const akwa_ibom = {
    id: uuid4,
    state_id: "AK",
    state_name: "Akwa Ibom",
    capital: "Uyo",
    motto: "Land of Promise",
    zone: "South South",
    cordinates: {
        lat: 4.940863799511036,
        lon: 7.8412267,
    },
    population: 7200000,
    land_area: 7081,
    governor: "Umo Eno",
    governor_party: "PDP",
    economic_activity: ["Oil & Gas", "Tourism", "Fishing"],
    LGAs: {
        total: 31,
        LGA_data: [
            {
                name: "Abak",
                headquaters: "Abak",
                population: 194500,
                land_area: 190,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand", "Clay"],
            },
            {
                name: "Eastern Obolo",
                headquaters: "Okoroete",
                population: 60200,
                land_area: 117,
                mineral_resources: ["Crude Oil", "Natural Gas", "Salt", "Glass Sand"],
            },
            {
                name: "Eket",
                headquaters: "Eket",
                population: 242100,
                land_area: 176,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay"],
            },
            {
                name: "Esit Eket",
                headquaters: "Uquo",
                population: 89400,
                land_area: 214,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Essien Udim",
                headquaters: "Afaha Ikot Ebak",
                population: 261800,
                land_area: 296,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Gravel"],
            },
            {
                name: "Etim Ekpo",
                headquaters: "Utu Etim Ekpo",
                population: 154700,
                land_area: 189,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay"],
            },
            {
                name: "Etinan",
                headquaters: "Etinan",
                population: 235600,
                land_area: 174,
                mineral_resources: ["Crude Oil", "Glass Sand", "Clay"],
            },
            {
                name: "Ibeno",
                headquaters: "Upenekang",
                population: 115900,
                land_area: 1200,
                mineral_resources: ["Crude Oil (Major Hub)", "Natural Gas", "Salt"],
            },
            {
                name: "Ibesikpo Asutan",
                headquaters: "Nung Udoe",
                population: 189400,
                land_area: 178,
                mineral_resources: ["Crude Oil", "Clay", "Laterite"],
            },
            {
                name: "Ibiono-Ibom",
                headquaters: "Oko Ita",
                population: 258200,
                land_area: 395,
                mineral_resources: ["Crude Oil", "Coal (Traces)", "Limestone", "Clay"],
            },
            {
                name: "Ika",
                headquaters: "Urua Inyang",
                population: 103800,
                land_area: 117,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Ikono",
                headquaters: "Ibiaku Ntok Okpo",
                population: 186700,
                land_area: 407,
                mineral_resources: ["Crude Oil", "Limestone", "Clay", "Natural Gas"],
            },
            {
                name: "Ikot Abasi",
                headquaters: "Ikot Abasi",
                population: 182400,
                land_area: 454,
                mineral_resources: ["Crude Oil", "Natural Gas", "Aluminum (Smelter)", "Clay"],
            },
            {
                name: "Ikot Ekpene",
                headquaters: "Ikot Ekpene",
                population: 204300,
                land_area: 116,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Raffia"],
            },
            {
                name: "Ini",
                headquaters: "Odoro Ikpe",
                population: 139500,
                land_area: 320,
                mineral_resources: ["Limestone", "Gold (Traces)", "Clay", "Crude Oil"],
            },
            {
                name: "Itu",
                headquaters: "Itu",
                population: 175600,
                land_area: 306,
                mineral_resources: ["Crude Oil", "Natural Gas", "Limestone", "Sand"],
            },
            {
                name: "Mbo",
                headquaters: "Enwang",
                population: 147800,
                land_area: 365,
                mineral_resources: ["Crude Oil", "Natural Gas", "Salt", "Iron Ore"],
            },
            {
                name: "Mkpat-Enin",
                headquaters: "Mkpat Enin",
                population: 248900,
                land_area: 322,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Nsit-Atai",
                headquaters: "Odot",
                population: 105400,
                land_area: 170,
                mineral_resources: ["Crude Oil", "Clay", "Laterite"],
            },
            {
                name: "Nsit-Ibom",
                headquaters: "Afaha Offiong",
                population: 147200,
                land_area: 142,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay"],
            },
            {
                name: "Nsit-Ubium",
                headquaters: "Ikore Ekpene Enin",
                population: 177300,
                land_area: 242,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay"],
            },
            {
                name: "Obot Akara",
                headquaters: "Nto Edino",
                population: 201400,
                land_area: 239,
                mineral_resources: ["Crude Oil", "Natural Gas", "Gravel"],
            },
            {
                name: "Okobo",
                headquaters: "Okopedi",
                population: 142100,
                land_area: 343,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay"],
            },
            {
                name: "Onna",
                headquaters: "Abat",
                population: 169300,
                land_area: 210,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Oron",
                headquaters: "Oron",
                population: 121500,
                land_area: 70,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Oruk Anam",
                headquaters: "Ikot Ibritam",
                population: 240800,
                land_area: 518,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Udung-Uko",
                headquaters: "Eyofin",
                population: 76500,
                land_area: 76,
                mineral_resources: ["Crude Oil", "Natural Gas"],
            },
            {
                name: "Ukanafun",
                headquaters: "Ikot Akpa Nkuk",
                population: 176200,
                land_area: 254,
                mineral_resources: ["Crude Oil", "Natural Gas", "Silica Sand"],
            },
            {
                name: "Uruan",
                headquaters: "Idu",
                population: 161400,
                land_area: 410,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Sand"],
            },
            {
                name: "Urue-Offong/Oruko",
                headquaters: "Urue Offong",
                population: 102100,
                land_area: 173,
                mineral_resources: ["Crude Oil", "Natural Gas"],
            },
            {
                name: "Uyo",
                headquaters: "Uyo",
                population: 554900,
                land_area: 115,
                mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Gravel"],
            },
        ]
        
    }
  }

module.exports = akwa_ibom;