const uuid4 = require("uuid").v4;

const anambra = {
  id: uuid4,
  state_id: "AN",
  state_name: "Anambra",
  capital: "Awka",
  motto: "Light of the Nation",
  zone: "South East",
  cordinates: {
    lat: 6.2183135994341985,
    lon: 6.9531842,
  },
  population: 6850000,
  land_area_km2: 4844,
  governor: "Charles Soludo",
  governor_party: "APGA",
  economic_activity: ["Commerce", "Manufacturing", "Metalworking"],
  LGAs: {
    total: 21,
    LGA_data: [
      {
        name: "Aguata",
        headquaters: "Aguata",
        population: 521400,
        land_area: 195,
        mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Laterite"],
      },
      {
        name: "Anambra East",
        headquaters: "Otuocha",
        population: 234100,
        land_area: 236,
        mineral_resources: ["Crude Oil", "Natural Gas (Major Hub)", "Clay"],
      },
      {
        name: "Anambra West",
        headquaters: "Nzam",
        population: 242600,
        land_area: 604,
        mineral_resources: [
          "Natural Gas",
          "Crude Oil",
          "Fertile Alluvial Soil",
        ],
      },
      {
        name: "Anaocha",
        headquaters: "Neni",
        population: 395800,
        land_area: 171,
        mineral_resources: ["Kaolin", "Clay", "Natural Gas"],
      },
      {
        name: "Awka North",
        headquaters: "Achalla",
        population: 164200,
        land_area: 355,
        mineral_resources: ["Clay", "Iron Ore", "Sandstone"],
      },
      {
        name: "Awka South",
        headquaters: "Awka",
        population: 286500,
        land_area: 170,
        mineral_resources: ["Clay", "Iron Ore", "Limestone"],
      },
      {
        name: "Ayamelum",
        headquaters: "Anaku",
        population: 221800,
        land_area: 506,
        mineral_resources: ["Natural Gas", "Crude Oil", "Clay"],
      },
      {
        name: "Dunukofia",
        headquaters: "Ukpo",
        population: 134100,
        land_area: 39,
        mineral_resources: ["Kaolin", "Laterite", "Natural Gas"],
      },
      {
        name: "Ekwusigo",
        headquaters: "Ozubulu",
        population: 224700,
        land_area: 122,
        mineral_resources: ["Clay", "Natural Gas", "Sharp Sand"],
      },
      {
        name: "Idemili North",
        headquaters: "Ogidi",
        population: 612400,
        land_area: 115,
        mineral_resources: ["Kaolin", "Clay", "Laterite"],
      },
      {
        name: "Idemili South",
        headquaters: "Ojoto",
        population: 235600,
        land_area: 138,
        mineral_resources: ["Kaolin", "Natural Gas", "Clay"],
      },
      {
        name: "Ihiala",
        headquaters: "Ihiala",
        population: 421000,
        land_area: 304,
        mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Kaolin"],
      },
      {
        name: "Njikoka",
        headquaters: "Abagana",
        population: 210900,
        land_area: 111,
        mineral_resources: ["Clay", "Kaolin", "Iron Ore"],
      },
      {
        name: "Nnewi North",
        headquaters: "Nnewi",
        population: 238200,
        land_area: 72,
        mineral_resources: ["Industrial Hub", "Clay", "Laterite"],
      },
      {
        name: "Nnewi South",
        headquaters: "Ukpor",
        population: 315400,
        land_area: 174,
        mineral_resources: ["Kaolin", "Clay", "Natural Gas"],
      },
      {
        name: "Ogbaru",
        headquaters: "Atani",
        population: 325800,
        land_area: 407,
        mineral_resources: ["Crude Oil", "Natural Gas", "Clay", "Sand"],
      },
      {
        name: "Onitsha North",
        headquaters: "Onitsha",
        population: 195600,
        land_area: 36,
        mineral_resources: ["Commercial Hub", "Sand", "Laterite"],
      },
      {
        name: "Onitsha South",
        headquaters: "Fegge",
        population: 235100,
        land_area: 16,
        mineral_resources: ["Commercial Hub", "Sand"],
      },
      {
        name: "Orumba North",
        headquaters: "Ajalli",
        population: 245200,
        land_area: 236,
        mineral_resources: ["Lignite", "Limestone", "Clay"],
      },
      {
        name: "Orumba South",
        headquaters: "Umunze",
        population: 268400,
        land_area: 218,
        mineral_resources: ["Lignite", "Clay", "Sandstone"],
      },
      {
        name: "Oyi",
        headquaters: "Nteje",
        population: 239700,
        land_area: 181,
        mineral_resources: ["Kaolin", "Natural Gas", "Clay"],
      },
    ],
  },
};

module.exports = anambra;
