const uuid4 = require("uuid").v4();

const bauchi = {
  id: uuid4,
  state_id: "BA",
  state_name: "Bauchi",
  capital: "Bauchi",
  motto: "Pearl of Tourism",
  zone: "North East",
  cordinates: {
    lat: 10.622828399473097,
    lon: 10.028775399999999,
  },
  population: 8300000,
  land_area_km2: 45893,
  governor: "Bala Mohammed",
  governor_party: "PDP",
  economic_activity: ["Tourism", "Agriculture", "Mining"],
  LGAs: {
    total: 20,
    LGA_data: [
      {
        name: "Alkaleri",
        headquater: "Alkaleri",
        population: 472800,
        land_area: 5918,
        minaral_resources: [
          "Crude Oil (Kolmani)",
          "Limestone",
          "Kaolin",
          "Gypsum",
        ],
      },
      {
        name: "Bauchi",
        headquater: "Bauchi",
        population: 724100,
        Land_Area_sq_km: 3687,
        minaral_resources: ["Limestone", "Kaolin", "Granite", "Iron Ore"],
      },
      {
        name: "Bogoro",
        headquater: "Bogoro",
        population: 118400,
        land_area: 894,
        minaral_resources: ["Gemstones", "Kaolin", "Quartz"],
      },
      {
        name: "Dambam",
        headquater: "Dambam",
        population: 210600,
        land_area: 1077,
        minaral_resources: ["Potash", "Silica Sand", "Clay"],
      },
      {
        name: "Darazo",
        headquater: "Darazo",
        population: 348200,
        land_area: 3015,
        minaral_resources: ["Gold (Traces)", "Iron Ore", "Quartz", "Kaolin"],
      },
      {
        name: "Dass",
        headquater: "Dass",
        population: 122900,
        land_area: 535,
        minaral_resources: ["Gemstones", "Granite", "Tantalite"],
      },
      {
        name: "Gamawa",
        headquater: "Gamawa",
        population: 395300,
        land_area: 2925,
        minaral_resources: ["Potash", "Silica Sand", "Diatomite"],
      },
      {
        name: "Ganjuwa",
        headquater: "Kafin Madaki",
        population: 381600,
        land_area: 3218,
        minaral_resources: ["Kaolin", "Limestone", "Iron Ore"],
      },
      {
        name: "Giade",
        headquater: "Giade",
        population: 212500,
        land_area: 667,
        minaral_resources: ["Silica Sand", "Clay", "Potash"],
      },
      {
        name: "Itas/Gadau",
        headquater: "Itas",
        population: 315400,
        land_area: 1398,
        minaral_resources: ["Gypsum", "Silica Sand", "Clay"],
      },
      {
        name: "Jama'are",
        headquater: "Jama'are",
        population: 164200,
        land_area: 493,
        minaral_resources: ["Silica Sand", "Clay", "Potash"],
      },
      {
        name: "Katagum",
        headquater: "Azare",
        population: 398100,
        land_area: 1436,
        minaral_resources: ["Silica Sand", "Potash", "Kaolin"],
      },
      {
        name: "Kirfi",
        headquater: "Kirfi",
        population: 195700,
        land_area: 2371,
        minaral_resources: ["Limestone", "Gypsum", "Gemstones"],
      },
      {
        name: "Misau",
        headquater: "Misau",
        population: 355200,
        land_area: 1226,
        minaral_resources: ["Silica Sand", "Potash", "Kaolin"],
      },
      {
        name: "Ningi",
        headquater: "Ningi",
        population: 524300,
        land_area: 4625,
        minaral_resources: ["Tin Ore", "Cassiterite", "Columbite", "Gemstones"],
      },
      {
        name: "Shira",
        headquater: "Yana",
        population: 321800,
        land_area: 1321,
        minaral_resources: ["Silica Sand", "Clay", "Potash"],
      },
      {
        name: "Tafawa Balewa",
        headquater: "Tafawa Balewa",
        population: 310500,
        land_area: 2515,
        minaral_resources: ["Gemstones", "Kaolin", "Mica", "Magnetite"],
      },
      {
        name: "Toro",
        headquater: "Toro",
        population: 475200,
        land_area: 6932,
        minaral_resources: ["Tin", "Columbite", "Magnetite", "Gemstones"],
      },
      {
        name: "Warji",
        headquater: "Warji",
        population: 158400,
        land_area: 625,
        minaral_resources: ["Kaolin", "Limestone", "Iron Ore"],
      },
      {
        name: "Zaki",
        headquater: "Sakwa",
        population: 258900,
        land_area: 1436,
        minaral_resources: ["Silica Sand", "Potash", "Clay"],
      },
    ],
  },
};

module.exports = bauchi;
